
namespace Toolkit
{
    interface IXamlMetadataContainer
    {
        Windows.Foundation.Collections.IVector<Microsoft.UI.Xaml.Markup.IXamlMetadataProvider> MetadataProviders { get; };
    };

    [default_interface]
    unsealed runtimeclass XamlApplication : Microsoft.UI.Xaml.Application, IXamlMetadataContainer, Windows.Foundation.IClosable
    {
        XamlApplication(Windows.Foundation.Collections.IVector<Microsoft.UI.Xaml.Markup.IXamlMetadataProvider> providers);
        protected XamlApplication();
        protected void Initialize();

        Windows.Foundation.IClosable WindowsXamlManager{ get; };
        Boolean IsDisposed { get; };
    }
}
